---
resources:
- name: git-source
  type: git
  source:
    uri: https://github.com/alindnbrg/PocketHub.git

jobs:
- name: analyze
  plan:
  - get: git-source
    trigger: true
  - task: run-build
    file: git-source/ci/pipeline-task.yml
#     # config:
    #   platform: linux
    #   image_resource:
    #     type: docker-image
    #     source:
    #       repository: circleci/android
    #       tag: api-23-node
    #   inputs:
    #     - name: git-source
    #   run:
    #     path: uname
    #     args:
    #       - -a
