---
resources:
- name: PocketHub
  type: git
  source:
    uri: https://github.com/alindnbrg/PocketHub.git

jobs:
- name: analyze-source
  plan:
  - get: PocketHub
    trigger: true
  - task: run-build
    file: PocketHub/ci/pipeline-task.yml
#     # config:
    #   platform: linux
    #   image_resource:
    #     type: docker-image
    #     source:
    #       repository: circleci/android
    #       tag: api-23-node
    #   inputs:
    #     - name: git-source
    #   run:
    #     path: uname
    #     args:
    #       - -a
